### PR TITLE
Add CMake support

### PR DESCRIPTION
**Pull request by srmainwaring**
This PR adds support for the CMake build system.

Addresses #60

### Discussion points

- Upstream dependencies are pulled in using CMake FetchContent. ~~git submodule. This may result in conflicts for downstream CMake projects where these dependencies are resolved from system installs or are independently included in submodules.~~
- Static vs shared libraries - current version uses a mixture, mainly to resolve linking issues on macOS.

### Tasks

- [x] Remove CMake debug messages
- [ ] Include CMake for tests (defer to follow-up PR)
- [ ] Add to CI (defer to follow up PR)

### CODE REVIEW

**Comment by srmainwaring** [comment]
Had cause to revisit this and have updated using FetchContent (loosely based on google/or-tools as per suggestion above). Happy to restructure as needed.

**Comment by rwgk** [comment]
Thanks, LGTM, with my extremely superficial cmake background.

I could now do the manual step to get this merged ("submitted" is our actual term) internally, as I outlined before (https://github.com/pybind/pybind11_protobuf/issues/60#issuecomment-1028715138), which will then trigger the automatic export. But before I do so, one quick question:

It's not great that we don't have any testing. Are you interested in adding a minimal GHA workflow (e.g. just one platform) to exercise the new cmake files? In this PR, or separately?

**Comment by srmainwaring** [comment]
Sure, I’ll put together a workflow for Ubuntu latest that does a build and runs the tests.

I have one question about which versions of the dependencies to pin to in FetchContent. I have used the versions used in the or-tools project rather the the versions in this projects Bazel files because the latter combination had build issues on macOS. If consistency across build systems is needed then there’s a bit more to do there as well.

**Comment by rwgk** [comment]
> Sure, I’ll put together a workflow for Ubuntu latest that does a build and runs the tests.

Awesome, thanks!

> I have one question about which versions of the dependencies to pin to in FetchContent. I have used the versions used in the or-tools project rather the the versions in this projects Bazel files because the latter combination had build issues on macOS. If consistency across build systems is needed then there’s a bit more to do there as well.

My feeling: "more to do" can wait (future PR).

@laramiel what do you think?

General purely practical consideration:
* With the current setup it's a bit of grunge work for me to merge internally, therefore handling many small PRs is time consuming,
* but I wouldn't want to pack too much into one PR just for the sake of saving me some grunge work.

**Comment by mjcarroll** [comment]
Friendly ping @rwgk and @laramiel, we are looking to get this merged for use in our project.  Is there anything we can do to move this along?

**Comment by srmainwaring** [comment]
@mjcarroll - actually I think that's with me to put together a minimal workflow using the cmake build. If you're thinking of using this for gz-msgs and gz-transport bindings I'll get back on to it.

**Comment by srmainwaring** [comment]
@rwgk if you're ok with merging this as is that would help for sure. I'll raise an issue for the ci workflow which you can assign to me if you like.

**Comment by rwgk** [comment]
> @rwgk if you're ok with merging this as is that would help for sure. I'll raise an issue for the ci workflow which you can assign to me if you like.

Is there a reasonably easy way to print out a warning when cmake is run (the initial configure step)?

Something like:
```
WARNING: CI testing for pybind11_protobuf cmake is currently MISSING! (https://github.com/pybind/pybind11_protobuf/issues/104)
```

**Comment by srmainwaring** [comment]
> Is there a reasonably easy way to print out a warning when cmake is run (the initial configure step)?

Sure - this following should do it. I'll add it in.

```
message(status "WARNING: CI testing for pybind11_protobuf cmake is currently MISSING! (https://github.com/pybind/pybind11_protobuf/issues/104)")
```

**Comment by rwgk** [comment]
Thanks, looks great! I'll try to pull this in asap.

**Comment by srmainwaring** [comment]
GHW for cpplint, cppcheck and build on https://github.com/srmainwaring/pybind11_protobuf/tree/feature/cmake-ci. It is a branch off this PR.

I noticed that for the an ubuntu build the dependencies need to be built with `CMAKE_CXX_FLAGS="-fPIC". This can be done either on the command line when calling cmake, or defined in the top-level CMakeLists.txt, which is what I've done for the follow up PR.

If you prefer I can push the CI changes to this branch (and remove the warning).

**Comment by rwgk** [comment]
I tried to establish basic pre-commit checks, including cmake-format: #105

I don't really know what I'm doing but it seems to work as a start. Note that your cmake file have a lot of whitespace changes.

Idea from here:

I could remove your cmake files from #105 again and merge the rest.

Then you could rebase this PR, then run `pre-commit run --all-files` for the whitespace cleanup.

And yes: pushing the CI changes here would be ideal.

How does that sound?

**Comment by rwgk** [comment]
> I could remove your cmake files from https://github.com/pybind/pybind11_protobuf/pull/105 again and merge the rest.

I decided to go ahead and do that. #105 will hopefully auto-merge in a few minutes.

**Comment by rwgk** [comment]
> I decided to go ahead and do that. #105 will hopefully auto-merge in a few minutes.

All done. I think after you have this PR updated I will be able to import it very quickly.

**Comment by srmainwaring** [comment]
> I think after you have this PR updated I will be able to import it very quickly.

Rebased and updated with GHW and changes to satisfy pre-commit. I excluded the cpplint and cppcheck workflows as I think these can be included in the pre-commit workflow with appropriate hooks (I'm not familiar with pre-commit so don't have the changes to hand).

**Comment by rwgk** [comment]
I added a couple commits to show more information, so that we can more easily see what we are dealing with, or what has changed (e.g. comparing logs before/after some date), if there are issues in the future.

**Comment by rwgk** [comment]
When importing this PR via #108 the ubuntu-build / ubuntu-build workflow ran twice in parallel:

* ubuntu-build / ubuntu-build (pull_request)
* ubuntu-build / ubuntu-build (push)

There is a lot of auto-magic in the automatic export from the Google-internal repo to github that I don't understand. I believe it's best to not trigger on `push` at all, at least for now: 5b092ac

**Comment by rwgk** [comment]
Still works! (I have to push an "Approve GHA" button. I'll keep an eye out for that.)

**Comment by srmainwaring** [comment]
> Still works!

The last change following review feedback is more substantial. My fork's branches are no longer triggering CI on push - so hope this does not break.

**Comment by rwgk** [comment]
> The last change following review feedback is more substantial.

Is that  44a9c21?

> My fork's branches are no longer triggering CI on push - so hope this does not break.

I think GHA triggered:

https://github.com/pybind/pybind11_protobuf/actions/runs/4328340527

Does the time of the run make sense?

**Comment by srmainwaring** [comment]
> I think GHA triggered:

Yes you're right. I also updated the GHW yaml for the build on a branch to check and its ok. I hope the changes are what the reviewer had in mind. Only outstanding is the tests. If they are required for this PR I can add, otherwise I'd prefer to defer to a follow up.

**Comment by rwgk** [comment]
> I hope the changes are what the reviewer had in mind.

FYI I'll probably only get to re-import-exporting this on Tuesday. I need a quiet block of time when I can focus, to not make a mess between this PR, the internal equivalent, and the re-exported #108. (We're moving house this weekend which isn't helping.)

**Comment by srmainwaring** [comment]
No prob, there's no rush on my side. Good luck with the house move.

**Comment by srmainwaring** [comment]
@rwgk - could you trigger/approve the GHW pls.

**Comment by rwgk** [comment]
Update: This PR and #108 (auto-force-pushed from Google-internal change list) are exactly identical again.

**Comment by rwgk** [comment]
Merged via #108.

**Comment by srmainwaring** [comment]
Hi @rwgk - thanks for getting this reviewed and merged. I noticed that my authorship has been stripped from the commits in `main`. Is there any way of getting that fixed?

**Comment by rwgk** [comment]
FYI

PR #109 rolls back #108 (I don't know why the new PR isn't marked more obviously as a rollback).

Then I'll try a roll forward with a trick to set the original author. It's a bit of an experiments, I hope it'll work out.

**Comment by rwgk** [comment]
Small update: we tried very hard to convince our copybara tool to respect some original author setting, but it stubbornly keep using my name (#110). Will try more tomorrow (hopefully).

**Comment by srmainwaring** [comment]
Thanks @rwgk - much appreciated.

**Comment by rwgk** [comment]
It worked!

d824311a3416232ee1892d0d6270960765e141b5

It turns out, we had such a hard time yesterday because there's a bug in the copybara tool. Luckily that only affects pre-merge testing. In the merging step it propagates the original author information correctly.  —  Thanks a lot @laramiel for helping me in the troubleshooting!

**Pull request closed without merging**
